name: http_plus
description: >-
  package:http compatible client that can speak HTTP/2, maintain connections and fallback to HTTP/1.1.
version: 0.2.2
homepage: https://github.com/daadu/http_plus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.0.0
  http2: ^2.0.0
  http_parser: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.0
